---

- name: Show CPU/memory
  debug:
    msg:
      - "ansible_processor_vcpus: {{ ansible_processor_vcpus }}"
      - "ansible_memtotal_mb: {{ ansible_memtotal_mb }}"

- name: Define mariadb_innodb
  set_fact:
    mariadb_innodb: "{{ innodb }}"
  when: mariadb_innodb is undefined and innodb is defined

- name: Configure innodb
  template:
    src: innodb.cnf.j2
    dest: "{{ mariadb_config_dir }}/innodb.cnf"
    mode: '0644'
  when: mariadb_innodb is defined
  notify:
    - Restart MariaDB


#- name: start service mariadb
#  service:
#    name: mariadb
#    enabled: yes
#    state: started


- name: start service mariadb  # noqa no-changed-when
  shell: |
    systemctl status -l mariadb
    mkdir /etc/systemd/system/mariadb.service.d
    echo -e "[Service]\nTimeoutStartSec=120" > /etc/systemd/system/mariadb.service.d/startup-timeout.conf
    systemctl daemon-reload
    date
    systemctl start mariadb
    date
    systemctl status -l mariadb
  ignore_errors: yes
  register: _service

- name: Show
  debug:
    var: _service

- name: Show service  # noqa no-changed-when
  command: systemctl status -l mariadb
  register: _service

- name: Show
  debug:
    var: _service

- name: Set a priv for user root on localhost
  mysql_user:
    name: 'root'
    state: present
    login_unix_socket: "{{ mariadb_socket }}"
    check_implicit_admin: true
    priv: '*.*:ALL,GRANT'
  notify:
    - Restart MariaDB

- name: remove remote root
  mysql_user:
    user: root
    state: absent
    check_implicit_admin: true
    login_unix_socket: "{{ mariadb_socket }}"
    host: "{{ ansible_fqdn }}"

- name: ensure anonymous users are not in the database
  mysql_user:
    name: ''
    host: "{{ item }}"
    state: absent
    login_unix_socket: "{{ mariadb_socket }}"
  loop:
    - localhost
    - "{{ inventory_hostname }}"

- name: remove the test database
  mysql_db:
    name: test
    state: absent
    login_unix_socket: "{{ mariadb_socket }}"

- name: Create custom config path
  file:
    path: "{{ mariadb_config_dir }}"
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Define mariadb_innodb
  set_fact:
    mariadb_innodb: "{{ innodb }}"
  when: mariadb_innodb is undefined and innodb is defined

- name: Configure innodb
  template:
    src: innodb.cnf.j2
    dest: "{{ mariadb_config_dir }}/innodb.cnf"
    mode: '0644'
  when: mariadb_innodb is defined
  notify:
    - Restart MariaDB
