---

- name: Delete DB
  community.mysql.mysql_db:
    name: "{{ mariadb_db_name }}"
    state: absent
    login_unix_socket: "{{ mariadb_socket if mariadb_socket_authentication | bool else omit }}"
    login_user: "{{ mariadb_user if not mariadb_socket_authentication | bool else omit }}"
    login_password: "{{ mariadb_pwd if not mariadb_socket_authentication | bool else omit }}"
  when: mariadb_db_delete | bool

- name: Create database
  community.mysql.mysql_db:
    name: "{{ mariadb_db_name }}"
    state: present
    login_unix_socket: "{{ mariadb_socket if mariadb_socket_authentication | bool else omit }}"
    login_user: "{{ mariadb_user if not mariadb_socket_authentication | bool else omit }}"
    login_password: "{{ mariadb_pwd if not mariadb_socket_authentication | bool else omit }}"

- name: Create db user
  community.mysql.mysql_user:
    name: "{{ mariadb_db_user }}"
    password: "{{ mariadb_db_pwd | default(omit) }}"
    host: "{{ item }}"
    state: present
    login_unix_socket: "{{ mariadb_socket if mariadb_socket_authentication | bool else omit }}"
    login_user: "{{ mariadb_user if not mariadb_socket_authentication | bool else omit }}"
    login_password: "{{ mariadb_pwd if not mariadb_socket_authentication | bool else omit }}"
    priv: "{{ mariadb_db_name }}.*:ALL,GRANT"
  loop:
    - localhost
#    - "{{ inventory_hostname }}"
#    - "{{ ansible_hostname }}"
#    - 127.0.0.1
#    - ::1
