---

- name: Setup-repository RedHat
  when: ansible_os_family == 'RedHat'
  block:

    - name: Add external mariadb repository (RedHat)
      ansible.builtin.yum_repository:
        name: mariadb-main
        description: MariaDB Server
        baseurl: https://downloads.mariadb.com/MariaDB/mariadb-{{ mariadb_release }}/yum/rhel/$releasever/$basearch
        gpgkey: https://yum.mariadb.org/RPM-GPG-KEY-MariaDB
        gpgcheck: true
        enabled: true
        module_hotfixes: "{{ True if ansible_version.full is version('2.11', '>=') else omit }}"
      register: _yum_repo

    - name: Update package list (YUM)
      ansible.builtin.yum:
        list: updates
        update_cache: true
      when: _yum_repo.changed


- name: Setup-repository Debian
  when: ansible_os_family == 'Debian'
  block:

    - name: Install GPG
      ansible.builtin.apt:
        name: gnupg
        state: present

    - name: Import APT key from official MariaDB repository (Debian)
      ansible.builtin.apt_key:
        url: https://mariadb.org/mariadb_release_signing_key.asc

    - name: Add official MariaDB repository (Debian)
      ansible.builtin.apt_repository:
        repo: >
          deb [arch=amd64,arm64,ppc64el]
          https://downloads.mariadb.com/MariaDB/mariadb-{{ mariadb_release }}/repo/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} main
        filename: "mariadb-{{ mariadb_release }}"
        state: present
      register: _apt_repo

    - name: Update package list (APT)
      ansible.builtin.apt:
        force_apt_get: yes
        update_cache: yes
        cache_valid_time: 0
      when: _apt_repo.changed

- name: Gather the package facts
  ansible.builtin.package_facts:
    manager: auto

- name: Install package prerequisites
  ansible.builtin.package:
    name: "{{ mariadb_pre_packages }}"
    state: present

- name: Install core packages
  ansible.builtin.package:
    name: "{{ mariadb_packages }}"
    state: present

- name: Install additional packages
  ansible.builtin.package:
    name: "{{ mariadb_additional_packages }}"
    state: present
