---

- name: Setup-repository RedHat
  when: ansible_os_family == 'Suse'
  block:

    - name: Import RPM signing key
      ansible.builtin.rpm_key:
        key: https://rpm.mariadb.org/RPM-GPG-KEY-MariaDB
        state: present

    - name: Use external repository from mariadb.com
      ansible.builtin.template:
        src: mariadb-suse.repo.j2
        dest: /etc/zypp/repos.d/mariadb-main.repo
        mode: "0644"

    - name: Update package list
      community.general.zypper:
        name: zypper
        update_cache: true

- name: Setup-repository RedHat
  when: ansible_os_family == 'RedHat'
  block:

    - name: Use external repository from mariadb.com
      ansible.builtin.template:
        src: mariadb-redhat.repo.j2
        dest: /etc/yum.repos.d/mariadb-main.repo
        mode: "0644"
      register: _yum_repo

    - name: Update package list (DNF)  # noqa no-handler
      ansible.builtin.dnf:
        list: updates
        update_cache: true
      when: _yum_repo.changed

- name: Setup-repository Debian
  when: ansible_os_family == 'Debian'
  block:

    - name: Install GPG
      ansible.builtin.apt:
        name: gnupg
        state: present

    - name: Download APT signing key
      ansible.builtin.get_url:
        url: https://mariadb.org/mariadb_release_signing_key.asc
        dest: /tmp/mariadb.asc
        mode: "0644"
      changed_when: false

    - name: Convert APT key into binary format
      ansible.builtin.command:
        cmd: gpg --batch --yes --no-tty --dearmor -o /tmp/mariadb.gpg /tmp/mariadb.asc
      changed_when: false

    - name: Import mariadb.org GPG key
      ansible.builtin.apt_key:
        state: present
        file: /tmp/mariadb.gpg
        keyring: /etc/apt/trusted.gpg.d/mariadb.gpg
      become: yes
      when: ansible_distribution_major_version | int < 12

    - name: Copy APT signing key into the proper drop-in directory
      ansible.builtin.copy:
        src: /tmp/mariadb.gpg
        dest: /etc/apt/trusted.gpg.d/mariadb.gpg
        remote_src: yes
        mode: "0644"
      when: ansible_distribution_major_version | int >= 12

    - name: Setup mariadb.org APT repository  # noqa jinja[spacing]
      ansible.builtin.apt_repository:
        repo: >-
          {%- if ansible_distribution_major_version | int < 12 -%}
          deb [arch=amd64,arm64]
          {{  mariadb_repo }}
          {{ ansible_distribution_release }}
          main
          {%- else -%}
          deb [arch=amd64,arm64 signed-by=/etc/apt/trusted.gpg.d/mariadb.gpg]
          {{  mariadb_repo }}
          {{ ansible_distribution_release }}
          main
          {%- endif -%}
        filename: "mariadb-{{ mariadb_release }}"
        state: present
      become: yes
      register: _apt_repo

    - name: Update package list (APT)  # noqa no-handler
      ansible.builtin.apt:
        force_apt_get: yes
        update_cache: yes
        cache_valid_time: 0
      when: _apt_repo.changed

- name: Gather the package facts
  ansible.builtin.package_facts:
    manager: auto

- name: Install package prerequisites
  ansible.builtin.package:
    name: "{{ mariadb_pre_packages }}"
    state: present

- name: Install core packages
  ansible.builtin.package:
    name: "{{ mariadb_packages }}"
    state: present

- name: Install additional packages
  ansible.builtin.package:
    name: "{{ mariadb_additional_packages }}"
    state: present
