---

- name: Load variables based on OS type
  include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
        - '{{ ansible_distribution }}.yml'
        - "{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
        - '{{ ansible_os_family }}.yml'
        - default.yml
      paths:
        - 'vars'

- include_tasks: install-vendor.yml
- include_tasks: config.yml
- include_tasks: db.yml

