---

- name: Assertions
  ansible.builtin.assert:
    that:
      - mariadb_release is defined

- name: Load variables based on OS type
  ansible.builtin.include_tasks: vars.yml

- name: Perform installation phase
  ansible.builtin.include_tasks: install.yml

- name: Perform configurarion phase
  ansible.builtin.include_tasks: config.yml

- name: Perform DB initialization
  ansible.builtin.include_tasks: db.yml
  when: mariadb_db_name is defined
