---

- name: Converge
  hosts: all
  become: "yes"
  vars:
    mariadb_release: 10.11
    mariadb_user: root
    mariadb_pwd: root1234
    mariadb_db_name: db01
    mariadb_db_user: user01
    mariadb_socket_authentication: True
  tasks:
    - name: Include role 'ansible-role-mariadb'
      ansible.builtin.include_role:
        name: ansible-role-mariadb
