---

dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ln -fs molecule/default/requirements.yml
  ansible-lint
  rm -f requirements.yml
platforms:

  - name: mariadb-rockylinux8-node1
    image: "geerlingguy/docker-rockylinux8-ansible:latest"
    rhsm: False
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: True
    pre_build_image: True
    dockerfile: Dockerfile.rockylinux8.j2

  - name: mariadb-rockylinux9-node1
    image: "geerlingguy/docker-rockylinux9-ansible:latest"
    rhsm: False
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: True
    pre_build_image: True
    dockerfile: Dockerfile.rockylinux9.j2

  - name: mariadb-debian11-node1
    image: "geerlingguy/docker-debian11-ansible:latest"
    rhsm: False
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: True
    pre_build_image: True
    dockerfile: Dockerfile.debian11.j2

  - name: mariadb-ubuntu2004-node1
    image: "geerlingguy/docker-ubuntu2004-ansible:latest"
    rhsm: False
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: True
    pre_build_image: True
    dockerfile: Dockerfile.ubuntu2004.j2

  - name: mariadb-ubuntu2204-node1
    image: "geerlingguy/docker-ubuntu2204-ansible:latest"
    rhsm: False
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: True
    pre_build_image: True
    dockerfile: Dockerfile.ubuntu2204.j2

provisioner:
  name: ansible

  env:
    ANSIBLE_PIPELINING: "True"
  lint:
    name: ansible-lint
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
  inventory:
    group_vars: {}
    host_vars: {}
scenario:
  name: default
verifier:
  name: ansible
