---

name: CI

on:
  pull_request:
  push:
  schedule:
    - cron: "0 7 * * 1"

defaults:
  run:
    working-directory: "de-it-krachten/ansible-role-mariadb"

jobs:

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2
        with:
          path: "${{ github.repository }}"

      - name: Set up Python 3.
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Show runner info
        run: |
          hostname -f
          lsb_release -a

      - name: Install test dependencies.
        run: pip3 install ansible ansible-lint yamllint jmespath

      - name: Lint code.
        run: |
          set -e
          yamllint .
          ansible-lint

  molecule-centos8:
    name: Molecule-centos8
    needs: lint
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2
        with:
          path: "${{ github.repository }}"

      - name: Set up Python 3.
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Show runner info
        run: |
          hostname -f
          lsb_release -a

      - name: Install test dependencies.
        run: pip3 install ansible ansible-lint molecule[docker] docker yamllint jmespath

      - name: Run Molecule tests.
        run: molecule test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: centos8
          MOLECULE_PLAYBOOK: converge.yml

  molecule-ubuntu2004:
    name: Molecule-ubuntu2004
    needs: molecule-centos8
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2
        with:
          path: "${{ github.repository }}"

      - name: Set up Python 3.
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Show runner info
        run: |
          hostname -f
          lsb_release -a

      - name: Install test dependencies.
        run: pip3 install ansible ansible-lint molecule[docker] docker yamllint jmespath

      - name: Run Molecule tests.
        run: molecule test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ubuntu2004
          MOLECULE_PLAYBOOK: converge.yml
